#!/bin/bash
RED='\033[1;31m'
YEL='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${YEL}$0" >> /tmp/eta_log
u=`/usr/bin/whoami`
echo -e "${YEL}$0 ${NC}running as ${YEL}$u" >> /tmp/eta_log

if [ ! -f /tmp/optic_touch.pid ]; then
    echo -e "${YEL}$0 ${NC}calling ${YEL}/usr/bin/eta-optictouch-busy &" >> /tmp/eta_log
    /usr/bin/eta-optictouch-busy &
fi

while [ ! -f /tmp/optic_touch.pid ]
do
    sleep 1
done

echo -e "${YEL}$0 ${NC}eta_gestemas check optic touch loop is ${GREEN}ok!" >> /tmp/eta_log
echo -e "${YEL}$0 ${NC}terminating every ${YEL}eta-optictouch-busy" >> /tmp/eta_log
killall eta-optictouch-busy
sleep 2

# When eta-gestemas crashes this loop brings it back.

while true; do
    /usr/bin/eta-gestemas
    sleep 1
done
