#!/bin/bash
RED='\033[1;31m'
YEL='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

LOG_FILE=/var/log/eta.log
OPTICTOUCH_PID=/var/run/optictouch.pid

echo -e "${YEL}$0" >> $LOG_FILE
u=`/usr/bin/whoami`
echo -e "${YEL}$0${NC} : running as ${YEL}$u" >> $LOG_FILE

# When eta-gestemas crashes this loop brings it back.

while true
do
    if [[ -f $OPTICTOUCH_PID ]]; then
        sleep 3
        echo -e "${YEL}$0${NC} : optictouch pid found calling ${YEL}/usr/bin/eta-gestemas" >> $LOG_FILE
        /usr/bin/eta-gestemas
    fi
    sleep 1
done
