#!/bin/bash

now=$(date +%d-%m-%Y\ %T.%3N)

RED='\033[1;31m'
YEL='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

LOG_FILE=/var/log/eta.log
OPTICTOUCH_PID=/var/run/optictouch.pid

print_output() {
  now=$(date +%d-%m-%Y\ %T.%3N)
  echo -e "$now $1" >> $LOG_FILE
}

print_output "${YEL}$0${NC}"
u=$(/usr/bin/whoami)
print_output "${YEL}$0${NC} : running as ${YEL}$u${NC}"

# When eta-gestemas crashes this loop brings it back.

while true
do
    pid=$(pgrep -f "/usr/bin/eta-gestemas")
    if [[ -f $OPTICTOUCH_PID ]]; then
        if [  -z "$pid" ]; then
            sleep 3
            print_output "${YEL}$0${NC} : optictouch pid found calling ${YEL}/usr/bin/eta-gestemas${NC}"
            /usr/bin/eta-gestemas &
        fi
    else
        if [ ! -z "$pid" ]; then
            now=$(date +%d-%m-%Y\ %T.%3N)
            print_output "${YEL}$0${NC} : optictouch pid not found terminating ${YEL}eta-gestemas${NC}"
            kill ${pid}
        fi
    fi
    sleep 1
done

